### ISSUE TITLE
How to enable modules

### ISSUE THREAD

**Issue by er-shrey** [m4ll0k/Galileo#5]
Please see the image and let us know what is happening:

![image](https://user-images.githubusercontent.com/29859866/49065743-e7798980-f244-11e8-87f2-3c781b45e3cc.png)

**Comment by NeilMascarenhas** [comment]
I am facing a similar issue. In fact, for me its showing 15 modules are disabled. 

![image](https://user-images.githubusercontent.com/16877823/49106372-0c074d00-f2a9-11e8-989d-b6602502a6fa.png)

**Comment by tony375** [comment]
python2 galileo.py
Traceback (most recent call last):
  File "galileo.py", line 8, in <module>
    from core import base
  File "/data/data/com.termux/files/home/Galileo/core/base.py", line 11, in <module>
    from core.framework import *
  File "/data/data/com.termux/files/home/Galileo/core/framework.py", line 22, in <module>
    from lib.request.gsocket import *
  File "/data/data/com.termux/files/home/Galileo/lib/request/gsocket.py", line 8, in <module>
    import socks
ImportError: No module named socks
CAN U PLZ HELP ME
